name = "lean_course_summer_26"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanCourseSummer26"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "verso-slides"
git = "https://github.com/leanprover/verso-slides.git"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanCourseSummer26"

[[lean_lib]]
name = "Exercises"

[[lean_lib]]
name = "Lecture1Slides"
srcDir = "lecture-notes"
roots = ["lecture1.lecture1"]

[[lean_exe]]
name = "lecture1-slides"
srcDir = "lecture-notes"
root = "lecture1.main"

[[lean_lib]]
name = "Lecture2Slides"
srcDir = "lecture-notes"
roots = ["lecture2.lecture2"]

[[lean_exe]]
name = "lecture2-slides"
srcDir = "lecture-notes"
root = "lecture2.main"
